#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

tmp_dir=$TARGET_ROOT/tmp/conda
mkdir -p $tmp_dir

PYTHON_VERSION="3"
CONDA_VERSION="5.2.0"
CONDA_DOWNLOAD_URL="https://repo.continuum.io/archive/Anaconda$PYTHON_VERSION-$CONDA_VERSION-Linux-x86_64.sh"

echo "Downloading Conda"
conda_file=$(basename "$CONDA_DOWNLOAD_URL")
cached_script="$DIB_IMAGE_CACHE/$conda_file"
$TMP_HOOKS_PATH/bin/cache-url $CONDA_DOWNLOAD_URL $cached_script
sudo install -D -g root -o root -m 0755 $cached_script $tmp_dir
echo "$CONDA_DOWNLOAD_URL" > $tmp_dir/conda_url.txt
