#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# We have to chown the Conda directories to make it usable for the default user
# Unfortunately the Ubuntu user does not exists when DIB is creating the image
# and we need to execute this code the first time the VM boots.

firstboot_script_name="/opt/conda/firstboot.sh"
if [ "$DISTRO_NAME" == "ubuntu" ]; then
     sed -i -e "s,^exit 0$,[ -f $firstboot_script_name ] \&\& sh $firstboot_script_name; exit 0," /etc/rc.local
     if [ "$plugin_type" == "vanilla" ]; then
         user_and_group_names="hadoop:hadoop"
     elif [ "$plugin_type" == "spark" ]; then
         user_and_group_names="ubuntu:ubuntu"
     fi
else
     sed -i -e "s,^exit 0$,[ -f $firstboot_script_name ] \&\& sh $firstboot_script_name; exit 0," /etc/rc.d/rc.local
     user_and_group_names="hadoop:hadoop"
fi

cat >> $firstboot_script_name <<EOF
#!/bin/sh

# 1. correct permissions
chmod 755 /opt/conda
chown -R $user_and_group_names /opt/conda

# 2. create and activate py34 conda env
source /opt/conda/anaconda3/etc/profile.d/conda.sh
conda create -y -n py34 python=3.4 anaconda
conda activate py34

# 3. add conda commands to ~/.bashrc
echo "source /opt/conda/anaconda3/etc/profile.d/conda.sh" >> /home/ubuntu/.bashrc
echo "conda activate py34" >> /home/ubuntu/.bashrc

# 4. install jupyterlab
conda install -c conda-forge jupyterlab

# 5. set jupyter notebook password (default: 080024hours)
jupyter notebook --generate-config
echo '{
  "NotebookApp": {
    "password": "sha1:03be4f0542e9:62fe2d3769488862a83d9e5e0b57bf546be0a157"
  }
}' > /home/ubuntu/.jupyter/jupyter_notebook_config.json

# 6. install toree
cd /opt/conda
tar xf toree-pip.tar
cd toree-pip
python setup.py install

# 7. install pyspark kernelspec
spark_master_ip=$(grep SPARK_MASTER_IP /opt/spark/conf/spark-env.sh | cut -d"=" -f2)
jupyter toree install --kernel_name=PySpark --spark_home=/opt/spark --spark_opts='--master=$(spark_master_ip):7077' --interpreters=PySpark --user

# 8. start jupyterlab in background
cd /
jupyterlab --ip=0.0.0.0 --no-browser &
disown

# 9. remove this script
rm $firstboot_script_name
EOF

